# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-mobile-extension}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["spanner"]
  s.date = %q{2010-11-10}
  s.description = %q{An easy, flexible, cache-friendly mobile version of your site}
  s.email = %q{will@spanner.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/views/admin/configuration/_edit_mobile.html.haml",
     "app/views/admin/configuration/_mobile.html.haml",
     "config/initializers/radiant_config.rb",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/mobile_page.rb",
     "lib/mobile_site_controller.rb",
     "lib/tasks/mobile_extension_tasks.rake",
     "mobile_extension.rb",
     "radiant-mobile-extension.gemspec",
     "spec/controllers/mobile_site_controller_spec.rb",
     "spec/models/mobile_page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/spanner/radiant-mobile-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Mobile Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/mobile_site_controller_spec.rb",
     "spec/models/mobile_page_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

